Repository Nuu-Project/Laravel-Project, pull requests merged in 2025-04, with the labels that each got.

#515 寄信 傳model 檔案名改叫Notification
  app/Http/Controllers/Web/Admin/MessageController.php
  app/Http/Controllers/Web/User/ProductMessageController.php
  app/Mail/CommentDeletedNotification.php
  app/Notifications/CommentDeletedNotification.php
  resources/views/components/table/message.blade.php
  routes/web/admin.php
  tests/Feature/Web/Admin/MessageControllerTest.php
Labels: frontend, backend

#516 自訂義驗證 ReportTypeRule UniqueReportRule
  app/Http/Controllers/Api/User/MessageReportController.php
  app/Http/Controllers/Api/User/ProductReportController.php
  app/Rules/Report/ReportTypeRule.php
  app/Rules/Report/UniqueReportRule.php
Labels: backend

#517 TEST Web: U: ProductMessage
  tests/Feature/Web/User/ProductMessageControllerTest.php
Labels: backend

#514 修正角色管理=>新增管理員:圖表會有一小格白框
  resources/views/admin/products/index.blade.php
  resources/views/admin/report-types/index.blade.php
  resources/views/admin/reports/index.blade.php
  resources/views/admin/roles/create.blade.php
  resources/views/admin/roles/index.blade.php
  resources/views/admin/users/index.blade.php
  resources/views/components/div/side-bar-admin.blade.php
  resources/views/components/navbar/side-bar-admin.blade.php
  resources/views/components/navbar/side-bar-user.blade.php
  resources/views/components/table/product.blade.php
  resources/views/components/table/report-message.blade.php
  resources/views/components/table/report-product.blade.php
  resources/views/components/table/report-type.blade.php
  resources/views/components/table/roles.blade.php
  resources/views/components/table/users.blade.php
  resources/views/guest/products/show.blade.php
Labels: frontend

#518 已註解但未刪除的code需移除(guest)
  resources/views/guest/products/show.blade.php
Labels: frontend

#519 留言管理與商品管理 的 檢舉詳情 filter[type] 的值 改 Enum
  resources/views/components/table/message.blade.php
  resources/views/components/table/product.blade.php
Labels: frontend

#520 管理者後台 檢舉詳情搜尋留言時未保留
  resources/views/admin/reports/index.blade.php
Labels: frontend

#521 TEST Web: U: Profile
  .env.testing
  .gitignore
  tests/Feature/Web/User/ProfileControllerTest.php
Labels: backend

#522 留言已編輯的位置修改和中文翻譯
  lang/zh_TW.json
  resources/views/guest/products/show.blade.php
Labels: frontend

#523 TEST Wed: A: User & UserFactory 新增 hasAdmin
  database/factories/UserFactory.php
  tests/Feature/Web/Admin/UserControllerTest.php
Labels: backend

#524 將Guest資料夾移動到Web底下
  tests/Feature/Web/Guest/ProductControllerTest.php
Labels: backend

#527 TEST Wed: A: Report && A: ReportType
  tests/Feature/Web/Admin/ReportControllerTest.php
  tests/Feature/Web/Admin/ReportTypeControllerTest.php
Labels: backend

#528 CommentDeletedNotification 改成 ProductMessageDeletedNotfication && roleCotrollerTest 字首改大寫
  app/Http/Controllers/Web/Admin/MessageController.php
  app/Notifications/ProductMessageDeletedNotification.php
  resources/views/mail/comment/deleted.blade.php
  tests/Feature/Web/Admin/RoleControllerTest.php
Labels: frontend, backend

#566 點驗證可以不用輸入密碼直接登入
  app/Http/Controllers/Auth/RegisteredUserController.php
Labels: backend

#565 RWD修正後Admin=> 全檔案 【Components製作】
  resources/views/admin/messages/index.blade.php
  resources/views/admin/products/index.blade.php
  resources/views/admin/reports/index.blade.php
  resources/views/admin/roles/create.blade.php
  resources/views/admin/roles/index.blade.php
  resources/views/admin/tags/index.blade.php
  resources/views/admin/users/index.blade.php
  resources/views/components/a/submit.blade.php
  resources/views/components/div/content-section.blade.php
  resources/views/components/div/red.blade.php
  resources/views/components/form/button-group.blade.php
  resources/views/components/form/container.blade.php
  resources/views/components/form/search-layout.blade.php
  resources/views/components/input/checkbox.blade.php
  resources/views/components/input/select.blade.php
  resources/views/components/responsive/container.blade.php
  resources/views/components/span/block-inline.blade.php
  resources/views/components/table/overflow-container.blade.php
  resources/views/components/td/center-left.blade.php
  resources/views/components/tr/hover.blade.php
Labels: frontend

#567 TEST 、Seeder修改
  database/seeders/DatabaseSeeder.php
  database/seeders/ReportTypeSeeder.php
  database/seeders/RoleSeeder.php
  tests/Feature/Web/Admin/MessageControllerTest.php
  tests/Feature/Web/Admin/ProductControllerTest.php
  tests/Feature/Web/Admin/ReportControllerTest.php
  tests/Feature/Web/Admin/ReportTypeControllerTest.php
  tests/Feature/Web/Admin/TagControllerTest.php
  tests/Feature/Web/User/ProductMessageControllerTest.php
  tests/Feature/Web/User/ProfileControllerTest.php
  tests/TestCase.php
Labels: backend

#568 Controller Web: U: Profile update 用戶驗證刪除
  app/Http/Controllers/Web/User/ProfileController.php
Labels: backend

#569 Controller Api: U: ProductProcessImage 中要加上圖片的驗證
  app/Http/Controllers/Api/User/ProductProcessImageController.php
Labels: backend

#570 Controller Web:U:ProductMessage 中的主留言刪除顯示方式更改
  app/Http/Controllers/Web/Guest/ProductController.php
  app/Models/Message.php
  database/migrations/2025_04_13_143531_add_deleted_at_to_messages_table.php
  resources/views/guest/products/show.blade.php
Labels: frontend, backend

#571 Factory Function名稱修改
  database/factories/MessageFactory.php
  database/factories/ProductFactory.php
  tests/Feature/Web/Admin/ReportControllerTest.php
Labels: backend

#572 修正Route Verb 來符合 RESTful API
  resources/views/components/table/product.blade.php
  resources/views/components/table/report-type.blade.php
  resources/views/components/table/tags.blade.php
  resources/views/components/table/users.blade.php
  resources/views/user/products/index.blade.php
  routes/web/admin.php
  routes/web/user.php
  tests/Feature/Web/Admin/ProductControllerTest.php
  tests/Feature/Web/Admin/ReportTypeControllerTest.php
  tests/Feature/Web/Admin/TagControllerTest.php
  tests/Feature/Web/Admin/UserControllerTest.php
Labels: backend

#573 登入index 元件需修正 (89行 label有錯字)
  resources/views/auth/login.blade.php
Labels: frontend

#574 新增TEST Web: U: ProductController
  -
  ProductStatusActive,
  database/seeders/RoleSeeder.php
  guest
  id,
  tests/Feature/Web/User/ProductControllerTest.php
  tests/TestCase.php
  user
  validation
Labels: backend

#575 洽談商品顯示圖修改
  public/css/info.css
  public/js/user/products/info.js
  resources/views/guest/products/show.blade.php
Labels: frontend

#577 刪除註解+登入上方列刪除+首頁連結icon
  resources/views/components/navbar/home.blade.php
  resources/views/user/products/index.blade.php
Labels: frontend

#579 商品顯示的排序
  app/Http/Controllers/Web/Guest/ProductController.php
Labels: backend

#580 RoleControllerTest程式縮減
  tests/Feature/Web/Admin/RoleControllerTest.php
  tests/Feature/Web/User/ProductMessageControllerTest.php
Labels: backend

#581 推薦書籍功能
  app/Http/Controllers/Web/Guest/HomeController.php
  resources/views/Home.blade.php
  resources/views/components/product/card.blade.php
Labels: frontend, backend

#583 登入介面修改+localhost回應 修改成正式回應
  resources/views/auth/login.blade.php
  resources/views/user/products/create.blade.php
Labels: frontend

#584 停用原因不可空白+帳號被停權 理由：
  public/js/admin/user.js
  resources/views/auth/login.blade.php
Labels: frontend

#585 檢舉留言與商品 錯誤訊息修改+"前往"到留言的位置
  public/js/admin/user.js
  public/js/user/products/info.js
  resources/views/components/table/message.blade.php
  resources/views/guest/products/show.blade.php
Labels: frontend

#586 TEST Api: U: MessageReportController
  tests/Feature/Api/User/MessageReportControllerTest.php
Labels: backend

#588 註解刪除
  resources/views/Home.blade.php
  resources/views/admin/roles/create.blade.php
  resources/views/admin/tags/edit.blade.php
  resources/views/admin/users/index.blade.php
  resources/views/auth/confirm-password.blade.php
  resources/views/auth/forgot-password.blade.php
  resources/views/auth/login.blade.php
  resources/views/auth/register.blade.php
  resources/views/auth/reset-password.blade.php
  resources/views/components/navbar/admin.blade.php
  resources/views/components/navbar/home.blade.php
  resources/views/components/navbar/user.blade.php
  resources/views/layouts/navigation.blade.php
Labels: frontend

#589 程式縮短
  -
  ProductStatusActive,
  guest
  id,
  tests/Feature/ExampleTest.php
  tests/Feature/Web/Admin/MessageControllerTest.php
  tests/Feature/Web/Admin/ProductControllerTest.php
  tests/Feature/Web/Admin/TagControllerTest.php
  tests/Feature/Web/Guest/ProductControllerTest.php
  tests/Unit/ExampleTest.php
  user
  validation
Labels: backend

#590 留言刪除通知信排版
  resources/views/mail/comment/deleted.blade.php
Labels: frontend

#591 驗證次數、有效時間設定
  app/Models/User.php
Labels: backend

#593 User=>Products=>三個檔案 【Components製作】
  resources/views/auth/login.blade.php
  resources/views/auth/register.blade.php
  resources/views/components/div/absolute.blade.php
  resources/views/components/div/rounded-full.blade.php
  resources/views/components/div/transition-enter.blade.php
  resources/views/components/div/transition-leave.blade.php
  resources/views/components/div/transition.blade.php
  resources/views/components/img/icon.blade.php
  resources/views/components/input/textarea.blade.php
  resources/views/components/label/form-sm.blade.php
  resources/views/components/p/text-gray.blade.php
  resources/views/components/p/text-muted.blade.php
  resources/views/components/product/actions.blade.php
  resources/views/components/product/empty-state.blade.php
  resources/views/components/product/image-uploader-edit.blade.php
  resources/views/components/product/image-uploader.blade.php
  resources/views/components/product/image.blade.php
  resources/views/components/product/tags.blade.php
  resources/views/components/product/user-card.blade.php
  resources/views/components/span/inline.blade.php
  resources/views/user/products/create.blade.php
  resources/views/user/products/edit.blade.php
  resources/views/user/products/index.blade.php
Labels: frontend

#605 TEST Web: U: Profile 程式縮短
  app/Http/Controllers/Web/User/ProfileController.php
  app/Http/Requests/ProfileUpdateRequest.php
  tests/Feature/ProfileTest.php
  tests/Feature/Web/User/ProfileControllerTest.php
Labels: backend

#613 TEST Wed: A: User 程式縮短
  tests/Feature/Web/Admin/UserControllerTest.php
  tests/TestCase.php
Labels: backend

#615 TEST Wed: A: ReportType 程式縮短
  tests/Feature/Web/Admin/ReportTypeControllerTest.php
Labels: backend

#616 Test Unit 還原
  tests/Unit/ExampleTest.php
Labels: backend

#617 停用帳號不能停用自己
  app/Http/Controllers/Api/Admin/UserSuspendController.php
  tests/Feature/Api/Admin/UserSuspendControllerTest.php
  tests/Feature/Web/Admin/RoleControllerTest.php
  tests/TestCase.php
Labels: backend

#618 TEST Wed: A: User actingAsAdmin()修正
  tests/Feature/Web/Admin/UserControllerTest.php
Labels: backend

#619 Test :ProductController 修正
  tests/Feature/Web/Guest/ProductControllerTest.php
Labels: backend

#620 重複無意義Components移除 & 首頁底部設置申訴表單連結
  app/Http/Controllers/Api/User/ProductProcessImageController.php
  app/Http/Controllers/Web/User/ProductController.php
  public/js/admin/roles/create.js
  public/js/product-editor.js
  resources/views/admin/products/index.blade.php
  resources/views/admin/report-types/index.blade.php
  resources/views/admin/roles/create.blade.php
  resources/views/admin/roles/index.blade.php
  resources/views/admin/tags/create.blade.php
  resources/views/admin/tags/edit.blade.php
  resources/views/components/div/overflow.blade.php
  resources/views/components/h/h1-middle.blade.php
  resources/views/components/page/last.blade.php
  resources/views/components/product/image-uploader-edit.blade.php
  resources/views/guest/products/index.blade.php
  resources/views/guest/products/show.blade.php
  resources/views/user/products/create.blade.php
  resources/views/user/products/edit.blade.php
Labels: frontend, backend

#621 推薦書籍功能優化
  app/Http/Controllers/Web/Guest/HomeController.php
  database/migrations/2025_04_23_005715_add_index_to_updated_and_created_at_in_products_table.php
Labels: backend

#622 推薦書籍功能 pint
  app/Http/Controllers/Web/Guest/HomeController.php
Labels: backend

#624 重複檢舉如果有新東西則更新其內容
  app/Http/Controllers/Api/User/MessageReportController.php
  app/Http/Controllers/Api/User/ProductReportController.php
  app/Rules/Report/UniqueReportRule.php
  tests/Feature/Api/User/MessageReportControllerTest.php
  tests/Feature/Api/User/ProductReportControllerTest.php
Labels: backend

#625 TEST Auth\PasswordUpdate assertRedirect路徑修正
  tests/Feature/Auth/PasswordUpdateTest.php
Labels: backend

#629 刪除功能重複的東西
  app/Models/User.php
Labels: backend

#626 Message 位置換頁+首頁底部的icon
  lang/zh_TW.json
  public/css/info.css
  public/js/user/products/info.js
  resources/views/auth/login.blade.php
  resources/views/auth/register.blade.php
  resources/views/components/page/last.blade.php
  resources/views/components/table/message.blade.php
  resources/views/guest/products/show.blade.php
Labels: frontend

#630 推薦商品 排除已下架的商品
  app/Http/Controllers/Web/Guest/HomeController.php
Labels: backend

#633 JS註解移除
  public/js/admin/message/message.js
  public/js/admin/roles/create.js
  public/js/admin/roles/index.js
  public/js/admin/user.js
  public/js/product-editor.js
  public/js/product-uploader.js
  public/js/user/products/info.js
  resources/views/components/text-input.blade.php
  resources/views/profile/edit.blade.php
  resources/views/profile/update-password-form.blade.php
Labels: frontend
