Repository Nuu-Project/Laravel-Project, pull requests merged in 2025-02, with the labels that each got.

#310 修改停用時間顯示格式方式
  app/Http/Requests/Auth/LoginRequest.php
Labels: backend

#311 使用者檢舉Controller改名，移動至Api資料夾
  app/Http/Controllers/Api/User/ProductReportableController.php
  app/Http/Controllers/User/ReportableController.php
  resources/views/guest/products/show.blade.php
  routes/api/user.php
  routes/user.php
  routes/web.php
Labels: backend

#313 檢舉內文修改
  app/Http/Controllers/Api/User/ProductReportableController.php
  composer.json
  composer.lock
  public/js/user/products/info.js
Labels: frontend

#317 A: TagController 創建重複的tag檢查
  app/Http/Controllers/Admin/TagController.php
Labels: backend

#318 排版
  config/filesystems.php
Labels: backend

#319 ProductMessageController 檔名 和 store 修正
  app/Http/Controllers/User/ProductMessageController.php
Labels: backend

#321 reports表改名report_types 功能上相關修正
  app/Http/Controllers/Admin/ProductController.php
  app/Http/Controllers/Admin/ReportController.php
  app/Http/Controllers/Api/User/ProductReportableController.php
  app/Http/Controllers/Guest/ProductController.php
  app/Models/Message.php
  app/Models/Product.php
  app/Models/ReportType.php
  app/Models/Reportable.php
  app/Models/User.php
  database/migrations/2025_02_05_222957_rename_reports_to_reporttypes.php
  database/migrations/2025_02_05_224724_rename_report_id_in_reportables_table.php
  database/seeders/ReportSeeder.php
  public/js/user/products/info.js
  resources/views/admin/products/index.blade.php
  resources/views/admin/reports/index.blade.php
Labels: backend

#322 Components樣式刪減
  resources/views/Home.blade.php
  resources/views/admin/products/index.blade.php
  resources/views/admin/reports/index.blade.php
  resources/views/admin/roles/create.blade.php
  resources/views/admin/roles/index.blade.php
  resources/views/auth/login.blade.php
  resources/views/auth/register.blade.php
  resources/views/components/a/block-font-black.blade.php
  resources/views/components/a/block-hover.blade.php
  resources/views/components/a/login.blade.php
  resources/views/components/a/register.blade.php
  resources/views/components/div/card-box.blade.php
  resources/views/components/div/container-screen.blade.php
  resources/views/components/h/h1.blade.php
  resources/views/components/h/h4.blade.php
  resources/views/components/h/h6.blade.php
  resources/views/components/li/font-semibold.blade.php
  resources/views/components/navbar/home.blade.php
  resources/views/components/navbar/side-bar-admin.blade.php
  resources/views/components/navbar/side-bar-user.blade.php
  resources/views/components/page/last.blade.php
  resources/views/components/product/card.blade.php
  resources/views/components/span/font-semibold.blade.php
  resources/views/components/table/tags.blade.php
  resources/views/components/td/gray-200.blade.php
  resources/views/components/td/gray-500.blade.php
  resources/views/components/td/operate.blade.php
  resources/views/layouts/navigation.blade.php
Labels: frontend

#323 Report名稱修正 &刪除無用js
  app/Http/Controllers/Admin/ReportableController.php
  public/js/admin/check.js
  resources/views/admin/products/index.blade.php
  resources/views/admin/reportables/index.blade.php
  resources/views/components/navbar/side-bar-admin.blade.php
  resources/views/components/thead/reportable.blade.php
  routes/admin.php
Labels: backend

#324 首頁用Contorller
  app/Http/Controllers/Guest/HomeController.php
  routes/web.php
Labels: backend

#325 route web 將 guest 分離 & 首頁連結修改
  resources/views/auth/login.blade.php
  resources/views/auth/register.blade.php
  resources/views/components/navbar/home.blade.php
  resources/views/components/navbar/side-bar-admin.blade.php
  resources/views/components/navbar/side-bar-user.blade.php
  resources/views/layouts/guest.blade.php
  resources/views/layouts/navigation.blade.php
  routes/guest.php
  routes/web.php
Labels: frontend, backend

#326 排版
  routes/guest.php
Labels: backend

#327 api UserSuspend 分離
  app/Http/Controllers/Admin/UserController.php
  app/Http/Controllers/Api/Admin/UserSuspendController.php
  routes/admin.php
  routes/api/admin.php
  routes/web.php
Labels: backend

#328 將檔案放入web資料夾
  app/Http/Controllers/Web/Admin/MessageController.php
  app/Http/Controllers/Web/Admin/ProductController.php
  app/Http/Controllers/Web/Admin/ReportableController.php
  app/Http/Controllers/Web/Admin/RoleController.php
  app/Http/Controllers/Web/Admin/TagController.php
  app/Http/Controllers/Web/Admin/UserController.php
  app/Http/Controllers/Web/Guest/HomeController.php
  app/Http/Controllers/Web/Guest/ProductController.php
  app/Http/Controllers/Web/User/ProductController.php
  app/Http/Controllers/Web/User/ProductMessageController.php
  app/Http/Controllers/Web/User/ProfileController.php
  routes/web.php
  routes/web/admin.php
  routes/web/guest.php
  routes/web/user.php
Labels: backend

#336 TagController update資料驗證 ignore
  app/Http/Controllers/Web/Admin/TagController.php
Labels: backend

#343 Route api user改檔名 prefix修改
  resources/views/guest/products/show.blade.php
  routes/api/product.php
  routes/web.php
Labels: backend

#344 HomeController index 改__invoke
  app/Http/Controllers/Web/Guest/HomeController.php
  routes/web/guest.php
Labels: backend

#345 rollback 錯誤修正
  database/migrations/2024_10_10_103218_create_reports_table.php
Labels: backend

#346 限制 factories商品描述欄位字數至最多 50 個字
  database/factories/ProductFactory.php
Labels: backend

#347 Api 套件安裝
  bootstrap/app.php
  composer.json
  composer.lock
  config/sanctum.php
  database/migrations/2025_02_10_202722_create_personal_access_tokens_table.php
  routes/api.php
Labels: backend

#349 reports migrate、controller、model 修正
  app/Http/Controllers/Web/Admin/ProductController.php
  app/Http/Controllers/Web/Admin/ReportableController.php
  app/Models/Message.php
  app/Models/Product.php
  app/Models/User.php
  database/migrations/2025_02_08_163256_update_reportables_and_create_reports_table.php
Labels: backend

#350 判斷reports 表是否存在
  database/migrations/2025_02_08_163256_update_reportables_and_create_reports_table.php
Labels: backend

#351 管理者後台 檢舉相關畫面
  resources/views/admin/products/index.blade.php
  resources/views/admin/reportables/index.blade.php
Labels: frontend

#352 管理者後台 檢舉詳情 商品名稱加入判斷
  resources/views/admin/reportables/index.blade.php
Labels: frontend

#353 controller 使用者檢舉 驗證&創建修正
  app/Http/Controllers/Api/User/ProductReportableController.php
  app/Models/Reportable.php
Labels: backend

#354 processImage函式中的圖片儲存方式進行修改
  app/Http/Controllers/Api/User/ProductProcessImageController.php
Labels: backend

#355 User ProductController 圖片相關的儲存方式進行修改
  app/Http/Controllers/Web/User/ProductController.php
Labels: backend

#356 部分Components 命名方式統一
  resources/views/Home.blade.php
  resources/views/admin/messages/index.blade.php
  resources/views/admin/products/index.blade.php
  resources/views/admin/reportables/index.blade.php
  resources/views/admin/roles/create.blade.php
  resources/views/admin/roles/index.blade.php
  resources/views/admin/tags/create.blade.php
  resources/views/admin/tags/edit.blade.php
  resources/views/admin/tags/index.blade.php
  resources/views/admin/users/index.blade.php
  resources/views/components/div/center.blade.php
  resources/views/components/div/green.blade.php
  resources/views/components/div/justify.blade.php
  resources/views/components/div/opacity.blade.php
  resources/views/components/div/text-center.blade.php
  resources/views/components/flex-container.blade.php
  resources/views/components/gray-200.blade.php
  resources/views/components/gray-900.blade.php
  resources/views/components/name.blade.php
  resources/views/components/navbar/home.blade.php
  resources/views/components/p/font-black.blade.php
  resources/views/components/page/last.blade.php
  resources/views/components/product/card.blade.php
  resources/views/components/table/message.blade.php
  resources/views/components/table/tags.blade.php
  resources/views/components/tags.blade.php
  resources/views/components/thead/products.blade.php
  resources/views/components/thead/reportable.blade.php
  resources/views/components/thead/roles.blade.php
  resources/views/components/thead/user.blade.php
  resources/views/guest/products/index.blade.php
  resources/views/user/products/create.blade.php
  resources/views/user/products/edit.blade.php
  resources/views/user/products/index.blade.php
Labels: frontend

#358 telescope修正
  app/Providers/AppServiceProvider.php
  bootstrap/providers.php
Labels: backend

#320 圖片上傳測試-1
  public/images/donation-1.png
  public/images/donation-2.png
  public/images/donation-3.png
  public/images/donation-4.png
  public/images/donation-5.png
  public/images/donation-6.png
  public/images/feature-img.png
  public/images/footer-logo.png
  public/images/home-img.png
  public/images/humans.png
  public/images/logo.png
  public/images/logofix.png
  public/images/navbar-logo.png
  public/images/volunteers.png
  resources/views/user/products/create.blade.php
  routes/api/product.php
Labels: frontend, backend

#359 縮減檢舉創建程式碼
  app/Http/Controllers/Api/User/ProductReportableController.php
Labels: backend

#366 排版
  routes/web.php
Labels: backend

#367 Controller Report相關改名
  app/Http/Controllers/Api/User/ProductReportController.php
  app/Http/Controllers/Web/Admin/ReportController.php
  routes/api/product.php
  routes/web/admin.php
Labels: backend

#368 測試修正
  resources/views/user/products/create.blade.php
  routes/api/product.php
Labels: frontend, backend

#369 繼續檢查遺漏重複class之Component
  resources/views/components/button/arrow-l.blade.php
  resources/views/components/button/arrow-r.blade.php
  resources/views/components/div/red.blade.php
  resources/views/components/form.blade.php
  resources/views/components/h/h1-small.blade.php
  resources/views/components/label/form.blade.php
  resources/views/components/select/form.blade.php
  resources/views/guest/products/index.blade.php
  resources/views/guest/products/show.blade.php
  resources/views/user/products/create.blade.php
  resources/views/user/products/edit.blade.php
  resources/views/user/products/index.blade.php
Labels: frontend

#370 使用者檢舉 後端接收token
  bootstrap/app.php
  routes/api/product.php
Labels: backend

#377 User ProductController 功能測試&修改 1
  app/Http/Controllers/Web/User/ProductController.php
  resources/views/user/products/create.blade.php
Labels: frontend, backend

#378 (<x-name>改成 <x-th>)
  resources/views/components/table/message.blade.php
  resources/views/components/table/tags.blade.php
  resources/views/components/th.blade.php
  resources/views/components/thead/products.blade.php
  resources/views/components/thead/reportable.blade.php
  resources/views/components/thead/roles.blade.php
  resources/views/components/thead/user.blade.php
  resources/views/user/products/index.blade.php
Labels: frontend

#371 Merge pull request #2 from Nuu-Project/main
  resources/views/user/products/create.blade.php
  routes/api/product.php
Labels: frontend

#379 User ProductController 功能測試&修改 2
  app/Http/Controllers/Web/User/ProductController.php
Labels: backend

#380 新增使用者檢舉留言功能畫面
  public/js/user/products/info.js
  resources/views/guest/products/show.blade.php
Labels: frontend

#381 管理者 新增、修改、停用檢舉類別畫面
  resources/views/admin/message-reportables/index.blade.php
  resources/views/admin/report-categories/create.blade.php
  resources/views/admin/report-categories/edit.blade.php
  resources/views/admin/report-categories/index.blade.php
  resources/views/components/navbar/side-bar-admin.blade.php
  resources/views/components/table/message.blade.php
  routes/web/admin.php
Labels: frontend
