Repository Nuu-Project/Laravel-Project, pull requests merged in 2025-03, with the labels that each got.

#382 圖片移除 relation
  app/Http/Controllers/Web/User/ProductController.php
Labels: backend

#393 在producter中使用mediaDisk
  app/Http/Controllers/Web/User/ProductController.php
Labels: backend

#394 商品編輯 Tagtype 回傳修正
  app/Http/Controllers/Web/User/ProductController.php
Labels: backend

#395 回覆留言功能
  app/Http/Controllers/Web/Guest/ProductController.php
  app/Http/Controllers/Web/User/ProductMessageController.php
  app/Models/Message.php
  database/migrations/2025_03_05_195440_add_reply_to_id_to_messages_table.php
  resources/views/guest/products/show.blade.php
  routes/web/admin.php
  routes/web/user.php
Labels: frontend, backend

#397 原檢舉詳情名稱修正為檢舉管理
  app/Http/Controllers/Web/Admin/ReportController.php
  resources/views/admin/message-reportables/index.blade.php
  resources/views/admin/products/index.blade.php
  resources/views/admin/reports/index.blade.php
  resources/views/components/navbar/side-bar-admin.blade.php
  routes/web/admin.php
Labels: frontend, backend

#398 pint 格式化
  app/Http/Controllers/Web/Guest/ProductController.php
  app/Models/Message.php
Labels: backend

#399 商品和留言的檢舉詳情合併成一張Table(下拉選單選擇)
  resources/views/admin/reports/index.blade.php
Labels: frontend

#400 檢舉管理 修改查詢功能
  app/Enums/ReportType.php
  app/Http/Controllers/Web/Admin/ReportController.php
Labels: backend

#401 新增使用者檢舉留言功能
  app/Http/Controllers/Api/User/MessageReportController.php
  resources/views/guest/products/show.blade.php
  routes/api.php
  routes/api/message.php
  routes/api/product.php
Labels: backend

#402 增加whereNull('reply_to_id')讓回覆留言不會出現兩遍
  app/Http/Controllers/Web/Guest/ProductController.php
Labels: backend

#404 使用 HasTranslations 修正reportType name顯示
  resources/views/admin/reports/index.blade.php
Labels: frontend

#405 使用 HasTranslations 修正reportType name顯示
  app/Http/Controllers/Web/Guest/ProductController.php
Labels: backend

#408 route加斜線與s
  public/js/user/products/info.js
  resources/views/guest/products/show.blade.php
  routes/api/message.php
  routes/api/product.php
Labels: backend

#409 使用者的商品移除"刪除"按鈕跟刪除換行空白
  app/Http/Controllers/Web/User/ProductController.php
  resources/views/guest/products/show.blade.php
  resources/views/user/products/index.blade.php
Labels: frontend

#412 ProducterController 圖片儲存方式在優化使用addMediaFromDisk
  app/Http/Controllers/Web/User/ProductController.php
Labels: backend

#420 用戶管理的檢舉欄位清除
  resources/views/admin/users/index.blade.php
  resources/views/components/thead/user.blade.php
Labels: frontend

#421 管理者不能移除自己的角色
  app/Http/Controllers/Web/Admin/RoleController.php
Labels: backend

#422 回覆留言的格式要跟留言一致(刪除跟檢舉)
  resources/views/guest/products/show.blade.php
Labels: frontend

#435 Controller函式強制回傳型態 (Guest,api,user)
  app/Http/Controllers/Api/Admin/UserSuspendController.php
  app/Http/Controllers/Api/User/MessageReportController.php
  app/Http/Controllers/Api/User/ProductProcessImageController.php
  app/Http/Controllers/Api/User/ProductReportController.php
  app/Http/Controllers/Web/Admin/TagController.php
  app/Http/Controllers/Web/Guest/ProductController.php
  app/Http/Controllers/Web/User/ProductController.php
  app/Http/Controllers/Web/User/ProductMessageController.php
  config/media-library.php
  config/permission.php
  database/factories/RoleFactory.php
  database/migrations/2024_08_28_064738_create_permission_tables.php
  database/seeders/ProductSeeder.php
  database/seeders/ReportSeeder.php
  database/seeders/RoleSeeder.php
  database/seeders/TagSeeder.php
Labels: backend

#436 管理者查詢檢舉詳情的留言功能(畫面)
  resources/views/admin/reports/index.blade.php
Labels: frontend

#437 report_types 路徑改成 report-types
  app/Http/Controllers/Web/Admin/ReportTypeController.php
  resources/views/admin/report-types/create.blade.php
  resources/views/admin/report-types/edit.blade.php
  resources/views/admin/report-types/index.blade.php
  resources/views/components/navbar/side-bar-admin.blade.php
  routes/web/admin.php
Labels: frontend, backend

#439 修復停用功能
  public/js/admin/user.js
  routes/api/admin.php
Labels: backend

#441 留言檢舉 檢舉原因類型顯示錯誤
  app/Http/Controllers/Web/Guest/ProductController.php
  public/js/user/products/info.js
  resources/views/guest/products/show.blade.php
Labels: backend

#440 管理者後台的各Tables表【RWD修正】 原前端2/27-2
  resources/views/admin/messages/index.blade.php
  resources/views/admin/products/index.blade.php
  resources/views/admin/report-types/index.blade.php
  resources/views/admin/reports/index.blade.php
  resources/views/admin/roles/create.blade.php
  resources/views/admin/roles/index.blade.php
  resources/views/admin/tags/index.blade.php
  resources/views/admin/users/index.blade.php
  resources/views/components/button/blue-short.blade.php
  resources/views/components/button/red-short.blade.php
  resources/views/components/button/search.blade.php
  resources/views/components/button/status.blade.php
  resources/views/components/div/content-section.blade.php
  resources/views/components/div/flex-container.blade.php
  resources/views/components/div/gray-200.blade.php
  resources/views/components/div/overflow-x.blade.php
  resources/views/components/gray-900.blade.php
  resources/views/components/h/h2.blade.php
  resources/views/components/h/h3.blade.php
  resources/views/components/input/search.blade.php
  resources/views/components/select/filter.blade.php
  resources/views/components/table/gray-200.blade.php
  resources/views/components/table/message.blade.php
  resources/views/components/table/tags.blade.php
  resources/views/components/td/gray-900.blade.php
  resources/views/components/thead/products.blade.php
  resources/views/components/thead/reportable.blade.php
  resources/views/components/thead/roles.blade.php
  resources/views/components/thead/user.blade.php
  resources/views/components/tr/hover.blade.php
Labels: frontend

#442 修正檢舉類型顯示錯誤
  database/seeders/ReportSeeder.php
Labels: backend

#443 Controller函式強制回傳型態 、資料格式驗證validate統一 (admin)
  app/Http/Controllers/Web/Admin/ProductController.php
  app/Http/Controllers/Web/Admin/ReportController.php
  app/Http/Controllers/Web/Admin/ReportTypeController.php
  app/Http/Controllers/Web/Admin/RoleController.php
  app/Http/Controllers/Web/Admin/TagController.php
  app/Http/Controllers/Web/Admin/UserController.php
Labels: backend

#463 report_types restore 路徑修正
  resources/views/admin/report-types/index.blade.php
  routes/web/admin.php
Labels: backend

#464 下拉選單修復
  resources/views/components/navbar/home.blade.php
  resources/views/layouts/navigation.blade.php
  resources/views/layouts/template-admin.blade.php
  resources/views/layouts/template-login-register.blade.php
  resources/views/layouts/template-user.blade.php
  resources/views/layouts/template.blade.php
Labels: frontend

#465 回傳值帶資料的方式統一 (admin,user,Guest,api)
  app/Http/Controllers/Web/Admin/MessageController.php
  app/Http/Controllers/Web/Admin/ProductController.php
  app/Http/Controllers/Web/Admin/ReportController.php
  app/Http/Controllers/Web/Admin/ReportTypeController.php
  app/Http/Controllers/Web/Admin/RoleController.php
  app/Http/Controllers/Web/Admin/TagController.php
  app/Http/Controllers/Web/Admin/UserController.php
  app/Http/Controllers/Web/Guest/ProductController.php
  app/Http/Controllers/Web/User/ProductController.php
  app/Http/Controllers/Web/User/ProfileController.php
Labels: backend

#467 創建假資料Factory
  app/Models/Report.php
  database/factories/MessageFactory.php
  database/factories/ProductFactory.php
  database/factories/ReportFactory.php
  database/factories/ReportTypeFactory.php
  database/factories/TagFactory.php
Labels: backend

#466 恢復刪除按鈕(使用者商品)
  app/Http/Controllers/Web/User/ProductController.php
  resources/views/user/products/index.blade.php
Labels: frontend, backend

#470 用Enum case 迭代
  app/Http/Controllers/Web/User/ProductController.php
  resources/views/admin/reports/index.blade.php
  resources/views/guest/products/index.blade.php
Labels: frontend, backend

#471 pint
  app/Http/Controllers/Web/User/ProductController.php
Labels: backend

#472 Route Reports 刪除 show
  routes/web/admin.php
Labels: backend

#469 確認使用者只能修改自己的東西
  app/Http/Controllers/Web/User/ProductController.php
  app/Http/Controllers/Web/User/ProductMessageController.php
  app/Http/Controllers/Web/User/ProfileController.php
Labels: backend

#473 檢舉功能檢查report_type_id 的 type
  app/Http/Controllers/Api/User/MessageReportController.php
  app/Http/Controllers/Api/User/ProductReportController.php
Labels: backend

#474 研究寄信提醒使用者的方法
  app/Http/Controllers/Web/User/ProductMessageController.php
  app/Mail/CommentDeletedNotification.php
  app/Models/User.php
  resources/views/mail/comment/deleted.blade.php
Labels: frontend, backend

#475 管理者【RWD修正】檢舉詳情&標籤管理
  resources/views/admin/tags/index.blade.php
  resources/views/admin/users/index.blade.php
  resources/views/components/div/bg-white.blade.php
  resources/views/components/div/gray-200.blade.php
  resources/views/components/input/search.blade.php
Labels: frontend

#476 啟用使用者帳號功能
  app/Http/Controllers/Web/Admin/UserController.php
  app/Models/User.php
  resources/views/admin/users/index.blade.php
  routes/web/admin.php
Labels: backend

#477 留言管理 檢舉詳情與前往功能
  app/Http/Controllers/Web/Admin/ReportController.php
  resources/views/admin/products/index.blade.php
  resources/views/components/table/message.blade.php
Labels: frontend

#479 資料建立到資料庫的方式統一 (admin,user,Guest,api)
  app/Http/Controllers/Api/Admin/UserSuspendController.php
  app/Http/Controllers/Api/User/MessageReportController.php
  app/Http/Controllers/Api/User/ProductReportController.php
  app/Http/Controllers/Web/User/ProductMessageController.php
  app/Models/User.php
Labels: backend

#478 測試編輯功能有無更新上去，原Edit回傳不回傳image[]資料(Put) +當使用者沒有上架商品時_顯示提示字 +檢舉別人只顯示檢舉欄位
  resources/views/guest/products/show.blade.php
  resources/views/user/products/edit.blade.php
  resources/views/user/products/index.blade.php
Labels: frontend

#480 ProfileController $user沒被定義
  app/Http/Controllers/Web/User/ProfileController.php
Labels: backend

#497 管理者停用按鈕與顯示畫面修改&把fetch請求的方式改成axios的方式處理request
  public/js/admin/user.js
  resources/views/admin/users/index.blade.php
  resources/views/components/thead/user.blade.php
  resources/views/guest/products/index.blade.php
  resources/views/guest/products/show.blade.php
  resources/views/user/products/create.blade.php
  resources/views/user/products/edit.blade.php
Labels: frontend

#507 Button元件名稱=>create-edit 改成submit
  resources/views/admin/report-types/create.blade.php
  resources/views/admin/report-types/edit.blade.php
  resources/views/admin/tags/create.blade.php
  resources/views/admin/tags/edit.blade.php
  resources/views/components/button/submit.blade.php
  resources/views/user/products/create.blade.php
  resources/views/user/products/edit.blade.php
Labels: frontend

#504 已註解但未刪除的code需移除
  resources/views/admin/messages/index.blade.php
  resources/views/admin/products/index.blade.php
  resources/views/admin/report-types/create.blade.php
  resources/views/admin/report-types/edit.blade.php
  resources/views/admin/report-types/index.blade.php
  resources/views/admin/reports/index.blade.php
  resources/views/admin/roles/create.blade.php
  resources/views/admin/roles/index.blade.php
  resources/views/admin/tags/create.blade.php
  resources/views/admin/tags/edit.blade.php
  resources/views/admin/tags/index.blade.php
  resources/views/admin/users/index.blade.php
  resources/views/layouts/app.blade.php
  resources/views/layouts/guest.blade.php
  resources/views/layouts/navigation.blade.php
  resources/views/layouts/template-admin.blade.php
  resources/views/layouts/template-login-register.blade.php
  resources/views/layouts/template-user.blade.php
  resources/views/layouts/template.blade.php
Labels: frontend

#503 TEST Api: A: UserSuspend && U: ProductReport
  .env.testing
  app/Http/Controllers/Web/Admin/RoleController.php
  app/Models/User.php
  tests/Feature/Api/Admin/UserSuspendControllerTest.php
  tests/Feature/Api/User/ProductReportControllerTest.php
  tests/Feature/Web/Admin/roleControllerTest.php
Labels: backend

#513 建立test
  app/Http/Controllers/Web/Guest/ProductController.php
  tests/Feature/Guest/ProductControllerTest.php
  tests/Feature/Web/Admin/MessageControllerTest.php
  tests/Feature/Web/Admin/ProductControllerTest.php
  tests/Feature/Web/Admin/TagControllerTest.php
Labels: backend
